"use client";

import React, { JSX } from "react";
import {
  Html5OriginalIcon,
  Css3OriginalIcon,
  JavascriptPlainIcon,
  TypescriptPlainIcon,
  ReactOriginalIcon,
  VuejsPlainIcon,
  AngularjsPlainIcon,
  NextjsOriginalIcon,
  NuxtjsOriginalIcon,
  SveltePlainIcon,
  NodejsPlainIcon,
  ExpressOriginalIcon,
  PythonPlainIcon,
  DjangoPlainIcon,
  FlaskOriginalIcon,
  GoPlainIcon,
  RailsPlainIcon,
  PhpPlainIcon,
  LaravelOriginalIcon,
  JavaPlainIcon,
  SpringOriginalIcon,
  SwiftPlainIcon,
  KotlinPlainIcon,
  AmazonwebservicesOriginalWordmarkIcon,
  GooglecloudPlainIcon,
  AzurePlainIcon,
  DockerPlainIcon,
  KubernetesPlainIcon,
  TerraformPlainIcon,
  PostgresqlPlainIcon,
  MysqlOriginalIcon,
  MongodbPlainIcon,
  RedisPlainIcon,
  PrismaOriginalIcon,
  CplusplusPlainIcon,
  CsharpPlainIcon,
  RustOriginalIcon,
  UnityOriginalIcon,
  UnrealengineOriginalIcon,
  TensorflowOriginalIcon,
  PytorchOriginalIcon,
  GraphqlPlainIcon,
  SupabasePlainIcon,
  FirebasePlainIcon,
  GitPlainIcon,
  FigmaPlainIcon,
  StorybookPlainIcon,
  JestPlainIcon,
  FlutterPlainIcon,
} from "@devicon/react";

// アイコン名とコンポーネントのマッピングオブジェクト
const iconMap: { [key: string]: JSX.Element } = {
  html5: <Html5OriginalIcon />,
  css3: <Css3OriginalIcon />,
  javascript: <JavascriptPlainIcon />,
  typescript: <TypescriptPlainIcon />,
  react: <ReactOriginalIcon />,
  vuejs: <VuejsPlainIcon />,
  angular: <AngularjsPlainIcon />,
  nextjs: <NextjsOriginalIcon />,
  nuxtjs: <NuxtjsOriginalIcon />,
  svelte: <SveltePlainIcon />,
  nodejs: <NodejsPlainIcon />,
  express: <ExpressOriginalIcon />,
  python: <PythonPlainIcon />,
  django: <DjangoPlainIcon />,
  flask: <FlaskOriginalIcon />,
  go: <GoPlainIcon />,
  rubyonrails: <RailsPlainIcon />,
  php: <PhpPlainIcon />,
  laravel: <LaravelOriginalIcon />,
  java: <JavaPlainIcon />,
  spring: <SpringOriginalIcon />,
  swift: <SwiftPlainIcon />,
  kotlin: <KotlinPlainIcon />,
  aws: <AmazonwebservicesOriginalWordmarkIcon />,
  googlecloud: <GooglecloudPlainIcon />,
  azure: <AzurePlainIcon />,
  docker: <DockerPlainIcon />,
  kubernetes: <KubernetesPlainIcon />,
  terraform: <TerraformPlainIcon />,
  postgresql: <PostgresqlPlainIcon />,
  mysql: <MysqlOriginalIcon />,
  mongodb: <MongodbPlainIcon />,
  redis: <RedisPlainIcon />,
  prisma: <PrismaOriginalIcon />,
  cplusplus: <CplusplusPlainIcon />,
  csharp: <CsharpPlainIcon />,
  rust: <RustOriginalIcon />,
  unity: <UnityOriginalIcon />,
  unrealengine: <UnrealengineOriginalIcon />,
  tensorflow: <TensorflowOriginalIcon />,
  pytorch: <PytorchOriginalIcon />,
  graphql: <GraphqlPlainIcon />,
  supabase: <SupabasePlainIcon />,
  firebase: <FirebasePlainIcon />,
  git: <GitPlainIcon />,
  figma: <FigmaPlainIcon />,
  storybook: <StorybookPlainIcon />,
  jest: <JestPlainIcon />,
  flutter: <FlutterPlainIcon />,
};

const DefaultIcon = <GitPlainIcon />; // デフォルトアイコン

export const SkillIcon = ({ iconName }: { iconName: string | null }) => {
  const IconComponent = iconName ? iconMap[iconName] : DefaultIcon;

  if (IconComponent) {
    return React.cloneElement(IconComponent, { size: 18 });
  }

  return React.cloneElement(DefaultIcon, { size: 18 });
};
